[package]
name = "attributes"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.3"
quote = "1.0.33"
syn = { version = "2.0.29", features = ["full", "parsing"] }
