[package]
name = "in-the-deep"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master"}
attributes = { path = "../attributes" }
derive = { path = "../derive"}
macros = { path = "../macros" }
